# Generated by Django 3.0.4 on 2020-04-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('form_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(default='', max_length=5000)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('cnic', models.CharField(default='', max_length=13)),
                ('address', models.CharField(default='', max_length=50)),
                ('addresss', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('number', models.CharField(default='', max_length=12)),
                ('country', models.CharField(default='', max_length=10)),
                ('city', models.CharField(default='', max_length=10)),
                ('item1', models.CharField(default='', max_length=50)),
                ('item2', models.CharField(default='', max_length=50)),
                ('item3', models.CharField(default='', max_length=50)),
                ('item4', models.CharField(default='', max_length=50)),
                ('item5', models.CharField(default='', max_length=50)),
                ('item6', models.CharField(default='', max_length=50)),
                ('item7', models.CharField(default='', max_length=50)),
                ('item8', models.CharField(default='', max_length=50)),
                ('quantity1', models.CharField(default='', max_length=50)),
                ('quantity2', models.CharField(default='', max_length=50)),
                ('quantity3', models.CharField(default='', max_length=50)),
                ('quantity4', models.CharField(default='', max_length=50)),
                ('quantity5', models.CharField(default='', max_length=50)),
                ('quantity6', models.CharField(default='', max_length=50)),
                ('quantity7', models.CharField(default='', max_length=50)),
                ('quantity8', models.CharField(default='', max_length=50)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=100, verbose_name='Last Name')),
                ('username', models.CharField(max_length=100, verbose_name='User Name')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='User email')),
                ('password', models.CharField(max_length=100, verbose_name='User password')),
                ('passwordd', models.CharField(max_length=100, verbose_name='User passwordd')),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
