# Generated by Django 3.0.4 on 2020-04-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity5',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity6',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity7',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity8',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.IntegerField(),
        ),
    ]
