# Generated by Django 3.0.4 on 2020-04-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200424_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity2',
            field=models.CharField(default='', max_length=50),
        ),
    ]
